___

<a href='https://jupyter-notebook.readthedocs.io/en/stable/examples/Notebook/Running%20Code.html'> <img src='https://www.python.org/static/img/python-logo.png' /></a>
___

# NumPy Ejercicios

Ahora que hemos aprendido sobre NumPy, probemos los conocimientos. Comenzaremos con algunas tareas simples y luego se harán algunas preguntas más complicadas.

#### Importar NumPy como np

In [1]:
import numpy as np

#### Crear un array de 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Crear un array de 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Crear un array de 10 cincos

In [9]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Crear un array de enteros desde 10 a 50

In [12]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### Cree una matriz de todos los enteros pares del 10 al 50

In [13]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Cree una matriz de 3x3 con valores que van de 0 a 8

In [14]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Crear una matriz de identidad de 3x3

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy para generar un número aleatorio entre 0 y 1

In [26]:
np.random.rand(1,1)

array([[0.08863738]])

#### Utilice NumPy para generar una matriz de 25 números aleatorios muestreados a partir de una distribución normal estándar

In [32]:
np.random.randn(5,5)

array([[-0.84637751,  0.07299584,  1.44073527, -0.35522093, -0.28096475],
       [ 0.89727506, -0.42531377, -0.05681756,  0.38413078, -0.79293323],
       [-0.42489721, -0.59390775, -1.08360659, -2.07411406,  0.72881945],
       [ 0.71604881,  0.11713095,  0.78101719,  0.385446  ,  1.13597661],
       [-0.12223265,  0.16314297,  0.28905528,  0.65986546,  0.27050113]])

#### Cree la siguiente matriz:

In [59]:
np.linspace(0,1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

#### Cree una matriz de 20 puntos espaciados linealmente entre 0 y 1:

In [60]:
np.linspace(0,1,20)


array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexación y Selección

Ahora se le darán algunas matrices y se le pedirá que replique los resultados de la matriz resultante:

In [62]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [63]:
# ESCRIBA AQUÍ EL CÓDIGO QUE REPRODUCE LA SALIDA DE LA CELDA A CONTINUACIÓN
# TENER CUIDADO DE NO HACER FUNCIONAR LA CELDA ABAJO, DE LO CONTRARIO NO
# PODRA VER LA SALIDA MÁS
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [66]:
# ESCRIBA AQUÍ EL CÓDIGO QUE REPRODUCE LA SALIDA DE LA CELDA A CONTINUACIÓN
# TENER CUIDADO DE NO HACER FUNCIONAR LA CELDA ABAJO, DE LO CONTRARIO NO
# PODRA VER LA SALIDA MÁS
# mat[mat==20]
mat[3,4]

20

20

In [80]:
# ESCRIBA AQUÍ EL CÓDIGO QUE REPRODUCE LA SALIDA DE LA CELDA A CONTINUACIÓN
# TENER CUIDADO DE NO HACER FUNCIONAR LA CELDA ABAJO, DE LO CONTRARIO NO
# PODRA VER LA SALIDA MÁS
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

array([[ 2],
       [ 7],
       [12]])

In [82]:
# ESCRIBA AQUÍ EL CÓDIGO QUE REPRODUCE LA SALIDA DE LA CELDA A CONTINUACIÓN
# TENER CUIDADO DE NO HACER FUNCIONAR LA CELDA ABAJO, DE LO CONTRARIO NO
# PODRA VER LA SALIDA MÁS
mat[4]

array([21, 22, 23, 24, 25])

array([21, 22, 23, 24, 25])

In [83]:
# ESCRIBA AQUÍ EL CÓDIGO QUE REPRODUCE LA SALIDA DE LA CELDA A CONTINUACIÓN
# TENER CUIDADO DE NO HACER FUNCIONAR LA CELDA ABAJO, DE LO CONTRARIO NO
# PODRA VER LA SALIDA MÁS
mat[[3,4]]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Ahora hacer lo siguiente

#### Obtenga la suma de todos los valores en mat

In [84]:
mat.sum()

325

#### Obtenga la desviación estándar de los valores en mat

In [86]:
np.std(mat)

7.211102550927978

#### Obtenga la suma de todas las columnas en mat

In [94]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [100]:
# np.sum(mat, axis=0)
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

# Buen trabajo!